Support Swift 5.4 (#68)
* Update swift.yml

* Update Package.swift

* Update NFCKitTagReaderSession.swift

* Update NFCKitNDEFReaderSession.swift

* Update NFCKitISO7816Tag.swift

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -103,6 +103,40 @@ jobs:
         name: swift test log (${{ matrix.os }}, x86_64)
         path: swift-test-${{ matrix.os }}_x86_64.log
   
+  xcodebuild_12-5-1_ios:
+    name: xcodebuild (12.5.1) (iOS)
+    runs-on: macos-11
+    needs: setup
+    steps:
+    - uses: actions/checkout@v2
+#     - name: Cache Gems
+#       uses: actions/cache@v2
+#       with:
+#         path: vendor/bundle
+#         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+#         restore-keys: |
+#           ${{ runner.os }}-gems-
+#     - name: Install Bundled Gems
+#       run: |
+#         bundle config path vendor/bundle
+#         bundle install --jobs 4 --retry 3
+#     - name: Download xcode-select path
+#       uses: actions/download-artifact@v2
+#       with:
+#         name: xcode-select
+    - name: Set xcode-select path
+      run: sudo xcode-select -s /Applications/Xcode_12.5.1.app # `cat xcode-select.txt`
+    - name: Xcode build
+      run: xcodebuild -scheme ${{ env.SCHEME_NAME }} -destination 'name=iPhone 12 mini' | tee xcodebuild-12.5.1-ios.log | xcpretty --color --report html && exit ${PIPESTATUS[0]}
+    - name: Upload xcode build report
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: xcodebuild log and report (iOS)
+        path: |
+            xcodebuild-12.5.1-ios.log
+            build/reports/build.html
+  
   xcodebuild_ios:
     name: xcodebuild (iOS)
     runs-on: macos-11
